import type { InstanceToggles } from '../../shared/types'

export function renderServerProperties(port: number, toggles: InstanceToggles): string {
  const lines: Record<string, string | number | boolean> = {
    'server-port': port,
    'online-mode': toggles.onlineMode,
    pvp: toggles.pvp,
    hardcore: toggles.hardcore,
    'white-list': toggles.whitelist,
    'enable-command-block': toggles.commandBlocksEnabled,
    'spawn-protection': toggles.spawnProtection,
    difficulty: toggles.difficulty,
    'view-distance': toggles.viewDistance,
    'max-players': 20,
    'motd': 'A Chunkforge Server'
  }

  return Object.entries(lines)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n')
}

export function renderEula(): string {
  return [
    '# Generated by Chunkforge.',
    '# By changing the setting below to TRUE you are indicating your agreement to the Minecraft EULA',
    '# (https://aka.ms/MinecraftEULA).',
    'eula=true'
  ].join('\n')
}
